[package]
name = "minigrep"
version = "0.1.0"
authors = ["Shylock-Hg <tcath2s@gmail.com>"]
edition = "2018"

[dependencies]
log={ features = ["max_level_trace", "release_max_level_warn"] }
stderrlog=""
